# Project Euler - Problem 2: Even Fibonacci Numbers
#
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.
# Answer: 4613732
#
# --- Notes ---
# - First attempt: confused summing consecutive integers (fib_val += n; n += 1)
#   with Fibonacci. Remember: Fibonacci needs the PREVIOUS TWO terms.
# - Second attempt: used a list to store the entire sequence. Works but
#   unnecessary — you only ever need the last two values, not the whole history.
#   Avoid storing more state than you need.
# - Learned: tuple unpacking (a, b = b, a + b) lets you update multiple
#   variables in one line without temp vars. Both sides evaluate before assignment.


def solve():
    a, b = 1, 2
    running_sum = 0
    while b < 4_000_000:
        if b % 2 == 0:
            running_sum += b
        a, b = b, a + b
    return running_sum


if __name__ == '__main__':
    print(solve())
